{% set name = "xpublish" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c11c8e42847670fdfab2fc35b37ff86ed5849974f40af7abf9f4578f00e9110

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - cachey
    - dask-core
    - fastapi >=0.78.0
    - numcodecs
    - numpy
    - pluggy
    - toolz
    - uvicorn
    # see https://github.com/xpublish-community/xpublish/issues/237
    - xarray !=2023.09.0
    - zarr

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - xpublish

about:
  home: https://xpublish.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Publish Xarray Datasets via a Zarr compatible REST API
  description: |
    Xpublish lets you serve, share and publish Xarray Datasets via a web application.
    The data and/or metadata in the Xarray Datasets can be exposed in various forms
    through pluggable REST API endpoints. Efficient, on-demand delivery of large
    datasets may be enabled with Dask on the server-side.
  doc_url: https://xpublish.readthedocs.io/
  dev_url: https://github.com/xarray-contrib/xpublish
extra:
  recipe-maintainers:
    - abkfenris
    - andersy005
    - jhamman
    - ocefpaf
